# Training Configuration
run_name: resnet50_fgvc_hiepronet_aliasinglabel # wandb will use this if not overridden
output_dir: ./output/online
seed: 42

# --- WandB ---
wandb_project: "HCL_fgvc_hiepronet_aliasing_label_resnet_cap1000_batch8_4"  # CHANGE THIS: Your W&B project name
wandb_entity: "dudusama"      # CHANGE THIS: Your W&B username or team (optional)
wandb_log_freq: 100               # Log model gradients/parameters every N batches with wandb.watch
wandb_mode: "offline"              # "online", "offline", "disabled"

# Data
dataset: fgvc
data_path: ./data
batch_size: 8
num_workers: 4
shuffle_train: True
num_tasks: 50
num_classes: 100
overlap_ratio: 0.2
split_ratio: 0.2
supervision: 'aliasing' # 'fine-grain' or 'full-label' or 'aliasing'

# Model
backbone_name: resnet50
pretrained_path: ./pretrained/dino_resnet50_pretrain.pth
freeze_backbone: False
add_heads:
  L1_head: 100
  L2_head: 100
  L3_head: 100
primary_head: 'L3_head'
head_type: ['linear', 'protonet', 'acil']
proto_format: 'hiepronet' # 'iciclenet' or 'protonet' or 'prototree'
return_features: False # Whether to return features from the backbone
return_protofeatures: True
feature_source: 'c4'
features_to_return: ['c4', 'pool']
proto_dim: 256
expansion_dim: 4096
# ensemble_temps: {'head[1, 1, 1] # Temperature for each head during ensemble

# Training Loop
epochs: 3
optimizer: AdamW
learning_rate: 0.0003
weight_decay: 0.0001
loss_function: 'hieproloss'
alpha: 0.5
loss_aggregation: 'mean' # 'mean' or 'sum' for multi-head loss

# Evaluation
eval_batch_size: 128
depth_bias: 0.9

# Logging (Python Logger)
log_level: INFO
log_interval: 100 # Log train loss to console/file every N batches
eval_interval: 100 # Log performance to console/file every N batches

# Memory Buffer
memory_name: 'Reservoir' # Memory Buffer 的名称
# memory_name: 'DHBRS' # Memory Buffer 的名称
memory_capacity: 1000  # Memory Buffer 的总容量
m_batch_size: 4       # Memory Buffer 的批次大小